config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  resources :users, only: [:create, :new, :index, :show] do
    resources :goals, only: [:create, :new]
  end
  resources :goals, only: [:update, :show]
  resources :comments, only: [:create, :destroy]
  resource :session, only: [:new, :create, :destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user_id, :commentable_type, :commentable_id, :body, presence: true

  belongs_to(
    :commentable,
    polymorphic: true
  )
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  user_id      :integer          not null
#  visibility   :string           not null
#  completeness :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Goal < ActiveRecord::Base
  Goal_Completeness = [
    "Complete",
    "Incomplete"
  ]
  Visibility = [
    "Public",
    "Private"
  ]
  validates :user_id, :title, :visibility, :completeness, presence: true
  validates :completeness, inclusion: Goal_Completeness
  validates :visibility, inclusion: Visibility
  after_initialize :set_to_incomplete!

  belongs_to(
    :user
  )

  has_many(
    :comments,
    as: :commentable,
    dependent: :destroy
  )

  def set_to_incomplete!
    self.completeness ||= "Incomplete"
  end

  def set_to_complete!
    self.completeness = "Complete"
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  before_validation :ensure_session_token!
  has_many(
    :goals,
    dependent: :destroy
  )

  has_many(
    :comments,
    as: :commentable,
    dependent: :destroy
  )

  def password=(password)
    @password =  password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token!
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token =  SecureRandom::urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.is_password?(password)
    nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user


  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def log_in!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to "/#{@comment.commentable_type.downcase}s/#{@comment.commentable_id}"
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to "/#{@comment.commentable_type.downcase}s/#{@comment.commentable_id}"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to "/#{@comment.commentable_type.downcase}s/#{@comment.commentable_id}"
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  include GoalsHelper
  def new
    @user = User.find(params[:user_id])
    @goal = Goal.new
    render :new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to user_url(@goal.user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end

  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to user_url(@goal.user_id)
    else
      flash[:errors] = ["Not sure why that failed"]
      redirect_to user_url(@goal.user_id)
    end
  end


  def show
    @goal = Goal.find(params[:id])
    render :show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password])
    if user
      log_in!(user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Invalid Username or Password!"]
      render :new
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def index
    @users = User.all
    render :index
  end

  def show
    @user = User.find(params[:id])
    render :show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    html = <<-HTML
      <input type="hidden"
            name="authenticity_token"
            value="#{form_authenticity_token}">
    HTML
    html.html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_params
    params.require(:comment).permit(:commentable_type, :commentable_id, :body)
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
  def goal_params
    params.require(:goal).permit(:title, :visibility, :completeness)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/views/goals/_comment.html.erb
<ul>
<% goal.comments.each do |comment| %>
  <li>
   <h4>Comment by <%= User.find(comment.user_id).username %></h4>
   <p><%= comment.body %></p>
 </li>
<% end %>
</ul>

app/views/goals/_comment_form.html.erb
<form action="/comments" method="POST">
  <%= auth_token %>
  <input type='hidden' name="comment[commentable_id]" value="<%= goal.id %>">
  <input type='hidden' name="comment[commentable_type]" value="Goal">
  <label>
    Comment <br>
    <textarea name="comment[body]"></textarea>
  </label>

  <input type="submit" value="Comment">
</form>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form action="<%= user_goals_url(@user) %>" method="POST">
  <%= auth_token %>

  <label>
    Goal
    <input type="text" name="goal[title]">
  </label>
  <br><br>

  <input type="radio" name="goal[visibility]" value="Private" id="private_visibility">
  <label for="private_visibility">Private</label><br>
  <input type="radio" name="goal[visibility]" value="Public" id="public_visibility">
  <label for="public_visibility">Public</label><br>

  <input type="submit" value="Create Goal!">
</form>

app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>

<%= @goal.completeness %>
<%= @goal.visibility %>

<%= render 'goals/comment', goal: @goal %>
<%= render 'goals/comment_form', goal: @goal %>

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/errors" %>
<% if current_user %>
  <%= current_user.username %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/_comment.html.erb
<ul>
<% user.received_comments.each do |comment| %>
  <li>
   <h4>Comment by <%= comment.poster.username %></h4>
   <p><%= comment.body %></p>
 </li>
<% end %>
</ul>

app/views/users/_comment_form.html.erb
<form action="/comments" method="POST">
  <%= auth_token %>
  <input type='hidden' name="comment[commentable_id]" value="<%= user.id %>">
  <input type='hidden' name="comment[commentable_type]" value="User">
  <label>
    Comment <br>
    <textarea name="comment[body]"></textarea>
  </label>

  <input type="submit" value="Comment">
</form>

app/views/users/_complete.html.erb
<form action="/goals/<%= goal.id %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="goal[completeness]" value="Complete">
  <input type="submit" value="Completed">
</form>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
<% @users.each do |user| %>
  <li><%= link_to user.username, user_url(user) %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="/users" method="POST">
  <%= auth_token %>

  <label>
    Username
    <input type="text" name="user[username]">
  </label>

  <label>
    Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<ul>
<% @user.goals.each do |goal| %>
  <% if (goal.visibility == 'Private' && current_user.id == goal.user_id) || goal.visibility == 'Public' %>
    <li>
      <%= link_to goal.title, goal_url(goal) %>,
      <%= goal.completeness %>,
      <%= goal.visibility %>
      <%= render('users/complete', goal: goal) if goal.completeness == "Incomplete" %>
    </li>
  <% end %>
<% end %>
</ul>

<% if current_user == @user %>
  <%= link_to "Create New Goal", new_user_goal_url(@user) %>
<% end %>

<%= render 'users/comment', user: @user %>
<%= render 'users/comment_form', user: @user %>